feat: add keepAlive to connections
snapshot-labs/keycard.js pull request #8
Opened 2023-09-01 16:18 UTC by wa0x6e

## 🧿 Current issues / What's wrong ?

Keycard API is being hit multiple times per seconds. All connections from services (score-api, hub) are using keycard.js, which is creating a new TCP connections per request.

Number of TCP connections per server is a limited resources, and creating a new one is creating overhead (DNS resolution, etc ...)

## 💊 Fixes / Solution

We should reuse the TCP connections whenever possible.

This will allow:
- faster connections (avoiding DNS overhead, etc ...)
- decrease number of concurrent TCP connections (reusing connections)

## 🚧 Changes

- Add 'agent' options to `fetch`, available only for node-fetch. Will not work on browser, but not our main use-case.

## 🛠️ Tests

- Use keycard from some other services (score-api)
- Analyze the http requests
- It should have the `keep-alive` header

2023-09-04 07:07 UTC, ChaituVR approved these changes
utAck

2023-09-04 08:05 UTC, ChaituVR commented
I don't see keep alive header somehow
<img width="570" alt="image" src="https://github.com/snapshot-labs/keycard.js/assets/15967809/23c08245-de71-49a1-a0d0-15ffcdf54fa8">

2023-09-04 15:13 UTC, ChaituVR commented
<img width="539" alt="Untitled" src="https://github.com/snapshot-labs/keycard.js/assets/15967809/d6e1743e-f4dc-4890-8816-4064514b4469">
Weird I still don't see it 🤔 not sure what I am missing, you are using which node version? I've tried it on 16 and 18

2023-09-04 15:18 UTC, wa0x6e commented
Node 16.20

2023-09-04 15:20 UTC, wa0x6e commented
Let's try the other way around.

Inside keycard, in rpc.ts, line 20, insert `console.log(req.headers);` and let's see what it does print

Mine is 

```
{
  accept: 'application/json',
  'content-type': 'application/json',
  secret: '1234',
  'content-length': '69',
  'user-agent': 'node-fetch/1.0 (+https://github.com/bitinn/node-fetch)',
  'accept-encoding': 'gzip,deflate',
  host: 'localhost:3007',
  connection: 'keep-alive'
}
```

2023-09-04 15:24 UTC, ChaituVR commented
Same `connection: 'close'` 🙈  @Todmy could you try on your side?

2023-09-05 07:59 UTC, Todmy requested changes

2023-09-05 08:23 UTC, Todmy commented
Same for me
<img width="639" alt="Screenshot 2023-09-05 at 10 22 10" src="https://github.com/snapshot-labs/keycard.js/assets/7693369/0e45fa68-0e9b-4dfc-bb46-a3c58fd35761">
But I don't see that `cross-fetch` supports ability to define `agent`

2023-09-05 10:31 UTC, wa0x6e commented on src/index.ts
> +const httpAgent = new http.Agent({ keepAlive: true });
That’s an idea, since our url is fixed

2023-09-05 14:20 UTC, wa0x6e commented
Code updated to use `node-fetch` directly, as well as timeout added. Can you try again to see if the headers are present ?

Another possible optimisation is to use `https://github.com/node-modules/agentkeepalive` to handle the agent, it's coming with some good default settings

2023-09-05 16:16 UTC, wa0x6e commented
Weird that it does not produce the expected result, implementation is coming from node-fetch own documentation https://github.com/node-fetch/node-fetch#custom-agent

2023-09-06 02:59 UTC, wa0x6e commented
@Todmy @ChaituVR can you run the test file in this PR https://github.com/snapshot-labs/keycard.js/pull/10 ?

2023-09-06 04:54 UTC, ChaituVR approved these changes
tAck

2023-09-06 04:57 UTC, merged